stages:
  - test

robot-tests:
  stage: test
  image: python:3.11
  script:
    - pip install -r requirements.txt
    - robot -d results tests-automation/malha-logistica-dental/tests/api/
  artifacts:
    paths:
      - results/
